apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: petpipeline
spec:
  selector:
    matchLabels:
      app: clickhouse
  serviceName: clickhouse
  replicas: 1
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:24.3-alpine
        ports:
        - containerPort: 8123
          name: http
        - containerPort: 9000
          name: native
        env:
        - name: CLICKHOUSE_DB
          value: app
        - name: CLICKHOUSE_USER
          value: dev
        - name: CLICKHOUSE_PASSWORD
          value: dev
        - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
          value: "1"
        volumeMounts:
        - name: data
          mountPath: /var/lib/clickhouse
        readinessProbe:
          httpGet:
            path: /ping
            port: 8123
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /ping
            port: 8123
          initialDelaySeconds: 20
          periodSeconds: 15
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
